fix: existingEntityNames are not filled in case microservice architecture is pre-choosen
if uaaAuthentication is false, the entitiesNames are not filled. That causes:

TypeError: Cannot read property 'forEach' of undefined
    at module.exports.writing (/usr/local/lib/node_modules/generator-jhipster-feign-client/generators/app/index.js:334:32)

Promt always the choice selection for uaa & microservice